name: Build and Release tfjs2tflite docker image

on:
  workflow_dispatch:

jobs:
  release-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: xizeyoupan
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: xizeyoupan/tfjs2tflite
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=ref,event=branch

      - name: Push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./cnn
